### ISSUE TITLE
HidBlocker blocks all HID access?

### ISSUE THREAD

**Issue by JoshWobbles** [nefarius/ViGEm#11]
If I understand the code correctly it blocks any and all requests for file creation on matched devices. Is it possible to white-list access or add an additional flag to the openfile call to allow HID access on a case by case basis?

**Comment by nefarius** [comment]
Correct. Yes, a simple whitelisting mechanism would be a good addition I guess. I'll look into it.

**Comment by nefarius** [comment]
Heya! [A solution was found](../tree/master/HidCerberus.Lib) 😄

**Comment by JoshWobbles** [comment]
Saw that the other day, sweet! Can't wait to play around with it.
