### ISSUE TITLE
While emulating xbox 360 controller a buggy audio device appears

### ISSUE THREAD

**Issue by Evengard** [nefarius/ViGEm#13]
When emulating an XBox 360 controller, it works fine... But it also sometimes (not every time, also not immediately) creates an audio device in the system. Windows (10 in my case) tends to try to use this device, which breaks something in ViGEmBus it seems, because after that and after a little while no input goes through, even though it get accepted by the driver.

The workaround is to disable this "rogue" device in the device manager, which seems to "fix" this issue (input still goes through, but still it is a kind of a pain tbh, especially when thinking about "how to instruct people about this shit".

Is it possible to do something with it?

PS: it happens with both the released 1.0.0.0 driver AND the latest compiled from master branch.

**Comment by nefarius** [comment]
Yes, I know. Haven't yet had the time to fix it but it's recorded 😃

**Comment by Evengard** [comment]
Do you have any tips what is it about? I looked through the source code but couldn't find the place where this device is created/managed in ViGEm.

**Comment by nefarius** [comment]
The device isn't created by ViGEm but by `xusb22.sys`

**Comment by Evengard** [comment]
I mean, how is it controlled from within ViGEm? Or it isn't actually, and you'll write something new to address this issue?

**Comment by nefarius** [comment]
It isn't controlled in any way. I assume I'm not catching a request issued by `XUSB.sys` properly so it "thinks" there is a headphone jack available. I looked through the code again and can't find an error in the descriptors so, yeah. More testing to be done once I have more time.

**Comment by charlesmilette** [comment]
Quick hack: hide the bugged device with HidGuardian

**Comment by mirh** [comment]
Weell.. Doesn't Xbox 360 controller have indeed an audio output?
If any, it seems like wiring this up properly should be the solution.

**Comment by charlesmilette** [comment]
It shows as "XBOX 360 Headset Driver" on mine.

**Comment by Evengard** [comment]
Really hope this bug gets addressed, it's a real blocker for me for using ViGEm.

**Comment by charlesmilette** [comment]
@nefarius So I've been asking zac_l (a Microsoft engineer roaming on the MS discord server) about this and he replied that this could be debugged by setting a breakpoint on IRP_MN_QUERY_DEVICE_RELATIONS. He also said he'll take a look after work.

**Comment by nefarius** [comment]
@charlesmilette oh cool! IRP_MN_QUERY_DEVICE_RELATIONS is "swallowed" by WDF so could very well be that this bug is only present in the WDF implementation. I took the exact same code from the ScpVBus source where this didn't happen.

**Comment by nefarius** [comment]
@charlesmilette any news on this dude? Cause I'm still stuck on this 😟

**Comment by charlesmilette** [comment]
Nope. I guess he didn't found out ¯\\\_(ツ)_/¯

**Comment by nefarius** [comment]
Finally discovered how to fix this, will be resolved in the next release 🎉

**Comment by nefarius** [comment]
This took only half a year to fix, kind of a personal record 😂

**Comment by mirh** [comment]
Speaking of stuff waiting for years, and given we are in this summer random mood, and given I have exams tomorrow and obviously I have to find just about anything that isn't studying to do
...
What's the long-term roadmap?
And can I use fireshock-vigem on 7?

**Comment by JoshWobbles** [comment]
@mirh  current vigem and fireshock drivers are both windows 7 signed.

**Comment by mirh** [comment]
Cool, because in a month or so I'll be testing it.. on Vista 😝

**Comment by JoshWobbles** [comment]
ewww. lol

**Comment by nefarius** [comment]
Jesus Christ...

**Comment by nefarius** [comment]
@mirh [Here you go](https://vigem.org/2017/06/16/vigem-framework-roadmap/) 😉

**Comment by mirh** [comment]
Uh, I feel important.
*sad not to see any airbender mention*

**Comment by nefarius** [comment]
To be honest; I'm a bit scared by AirBender. I can say that I built a pretty solid foundation of knowledge regarding USB and HID but Bluetooth in Windows Kernel-Mode is a whole different story. I know how the DS3 communication works but I don't know where to tap into the Windows Bluetooth Stack to replicate the user-mode logic used in ScpToolkit.

**Comment by mirh** [comment]
[Jesus hell](https://msdn.microsoft.com/it-it/library/windows/hardware/ff536587(v=vs.85).aspx), it's a clusterfuck. 
My immensely educated guess would be *HidBth*
Then everything else I know was already said in https://github.com/nefarius/ScpToolkit/issues/290...

@jloehr sup? 🙃

**Comment by jloehr** [comment]
Whaddup! 😄(More OT 😁)
My best guess would be HidBth as well. 
As far as i know/understand, you can't provide drivers for Bluetooth devices, but only for its profiles.
The underlying Bluetooth stack does all the pairing (Big issue for Wiimotes btw.), SDP and enumeration. Each profile that the devices supports is enumerated and a profile specific driver is loaded. Such profile driver can then talk to the device via L2CAP and its PSMs.
If you must do some special pairing or direct HCI commands, it seems you have to write a Bluetooth stack yourself, which is obviously overkill.

**Comment by nefarius** [comment]
@jloehr then there is no way around it; the DS3 has no/an invalid SDP so standards-compliant Bluetooth dongles are just like "lol what's this sh*t, man?!" and can't even pair it. That's why the ScpToolkit has/needs a full custom Bluetooth stack built in user-mode to make it work. This renders the dongle useless for other BT devices like keyboards, headsets, etc. which is surprisingly hard to understand/accept by a lot of my users... ("why keyboard no work no more, u broke mah PC, wääh, wääh") 🙄

**Comment by mirh** [comment]
Isn't SDP just needed for pairing?
DS3 certainly hasn't, but once bt MAC address is added to it via usual usb, why that should still be a stopper?

**Comment by nefarius** [comment]
I don't know for sure, I'd have to investigate and test again.

**Comment by mirh** [comment]
So.. Hoping I'm not bullshiting or making useless noise
As far as I understand the windows bt stack.. HID could even be mostly done actually
And in the graph SDP seems not a hard requirement for any module

The biggest difficulty [seems](https://github.com/felis/USB_Host_Shield_2.0/wiki/PS3-Information#bluetooth) to be figuring how L2CAP [server](https://msdn.microsoft.com/en-us/library/windows/hardware/ff536572(v=vs.85).aspx) and [profile](https://msdn.microsoft.com/en-us/library/windows/hardware/ff536674(v=vs.85).aspx) drivers maps to the 'linux instructions'. 
[HID Data](https://msdn.microsoft.com/en-us/library/windows/hardware/ff536621(v=vs.85).aspx) should be "[Interrupts](https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/profiles/input/device.h)" for example.
