### ISSUE TITLE
Old release (mostly of the signed version of the driver)

### ISSUE THREAD

**Issue by Evengard** [nefarius/ViGEm#14]
The only release of the 1.0.0.0 driver is quite old and doesn't have some modifications which are included in the master branch. As not everyone have access to software signing keys (especially for drivers), and instructing people to enable test signing is not really what should be done, please release (at least only the driver) the signed binaries from the master branch!

**Comment by Evengard** [comment]
Sorry for that close/reopen, missclick. Anyway it's of course still actual :)

**Comment by nefarius** [comment]
I agree. Fortunately I will soon have a full blown certificate so I can publish releases more frequently.

**Comment by JoshWobbles** [comment]
Ill be linking to your Patreon in my next IM release to hopefully drum up some support for ya.

**Comment by Evengard** [comment]
Wow good news! Waiting with impatience!

**Comment by NelsonRosenberg** [comment]
Any news on the new release? While Fireshock works well and I can use it in SF5, Vigem BSOD me and I'm not sure how to make it  emulate a xbox controller. A doc would be nice! Thanks a lot for your hard work.

**Comment by JoshWobbles** [comment]
Is your BSOD related tot he DPC leak reported in FireShock?

**Comment by NelsonRosenberg** [comment]
Don't think so. Fireshock worked, I only BSOD when installed VIGEm. I was unpluging the controller when it happened so that may be the reason. I did not test it much, sorry.

**Comment by JoshWobbles** [comment]
Fireshock itself wouldn't produce the BSOD as it does not show itself until the controller is actually "used". Still sounds possible it could be related. More info on the BSOD and DPC latency leading up to it is needed to determine.

**Comment by nefarius** [comment]
If you spout out something like this please always include OS Version and used Version numbers of the drivers, since there's so much change I can't approve or deny these claims.

**Comment by nefarius** [comment]
Plus open an issue and don't hijack other topic's threads.

**Comment by NelsonRosenberg** [comment]
Sorry, my intent was not to complain about the BSOD, I only mentioned it. I meant just to ask if the new release was near. It did even cross my mind to test the BSOD as I figured it would be a normal thing in a beta project.

If it makes any differences, OS is Windows 10 Pro 64x fully updated and I was using the latest release available on github (.exe)

**Comment by nefarius** [comment]
It'd be very near if the shitty M$ sysdev portal wouldn't always timeout 😠

**Comment by nefarius** [comment]
Well, at least I can now sign for Windows 10, will close this for now.
