### ISSUE TITLE
HidGuardian devcon.exe failed

### ISSUE THREAD

**Issue by viltis-projekt** [nefarius/ViGEm#15]
got devcon.exe failed and new unknown device after inputting `devcon.exe install HidGuardian.inf Root\HidGuardian` in cmd  
here's the full message :
`C:\Users\Administrator>devcon.exe install "G:\HidGuardian\HidGuardian.inf" Root\HidGuardian
Device node created. Install is complete when drivers are installed...
Updating drivers for Root\HidGuardian from G:\HidGuardian\HidGuardian.inf.
devcon.exe failed.`

sorry for my bad english

**Comment by nefarius** [comment]
This was resolved by mail.
