### ISSUE TITLE
HidGuardien; works well for USB and Sony Adapter, does not seem to work for BT.

### ISSUE THREAD

**Issue by JoshWobbles** [nefarius/ViGEm#17]
Not sure if its something you just haven't implemented yet, but the HidGuardian does not seem to block BT controllers from showing up in joy.cpl, only Sony Adapter and USB.

This is the filter I am using:

> HID\VID_054C&PID_05C4&REV_0100
> HID\VID_054C&PID_05C4
> HID\VID_054C&UP:0001_U:0005
> HID{00001124-0000-1000-8000-00805f9b34fb}_VID&0002054c_PID&05c4
> HID\VID_054C&PID_0BA0&REV_0100&MI_03
> HID\VID_054C&PID_0BA0&MI_03

**Comment by nefarius** [comment]
Is this still a thing? Sorry, haven't had the chance to replicate myself.

**Comment by JoshWobbles** [comment]
yes, Not sure why, but does not seem BT compatible.

**Comment by nefarius** [comment]
Can you open the troubled device in device manager and show me the value of the `Class` property?

**Comment by JoshWobbles** [comment]
I would love to do that, but I somehow fried my BT dongle and have just been using the Sony Adapter lately lol.

**Comment by nefarius** [comment]
Hang on, I could try myself with the DS4, I should expect the same issue, right?

**Comment by JoshWobbles** [comment]
otherwise i'm just a moron lol

**Comment by nefarius** [comment]
Challenge accepted 😆

**Comment by nefarius** [comment]
Seems to work on my end although the Hardware ID(s) for the DS4 connected over Bluetooth are the following on my system:
```
HID\{00001124-0000-1000-8000-00805f9b34fb}_VID&0002054c_PID&05c4
HID\{00001124-0000-1000-8000-00805f9b34fb}_LOCALMFG&000a
HID\VID_054C&UP:0001_U:0005
HID_DEVICE_SYSTEM_GAME
HID_DEVICE_UP:0001_U:0005
HID_DEVICE
```

![image](https://cloud.githubusercontent.com/assets/286631/25557688/8cf7541e-2d16-11e7-96fc-c8ba1ee0357e.png)

**Comment by JoshWobbles** [comment]
Interesting, dont think mine looked like that, is that GUID a HID or BT GUID?

**Comment by nefarius** [comment]
According to the internet that's the Bluetooth HID Device Service GUID (nice name).

**Comment by JoshWobbles** [comment]
Take that back, I did have that entry in mine aswell, do I need all of them, some seem pretty generic and could cause issues with other devices.

**Comment by nefarius** [comment]
Since it's a simple string comparison you'd only need the first line reported by the device.

**Comment by nefarius** [comment]
Also working with the new GUI 😄 

![image](https://cloud.githubusercontent.com/assets/286631/25557767/6d53cfdc-2d18-11e7-81f2-86ef1aede54d.png)

**Comment by JoshWobbles** [comment]
Well I definitely had that one, weird.

Possible to tweak this so we are just using HID's and PID's with a comma or bar seperator? Such as;
`0x054c|0x05c4`

**Comment by nefarius** [comment]
I'm going to abstract the direct registry manipulation away with a more convenient API anyways so don't worry too much about the input format. Internally I need the full string since I have limited possibilities on string manipulation in kernel mode.

**Comment by JoshWobbles** [comment]
Splitting a string is tricky in c kmdf, but can you not access the devices (for which the driver is loaded for) and take its VID and VID then build a string using strcat then strcmp that to each line in the reg? Just trying to find a way to trim those strings down a bit as I suspect it is somthing unique to my BT stack or device that may have resulted in my hardware ID's slightly different than yours.

**Comment by nefarius** [comment]
Yes but I want to avoid unnecessary workarounds. There are already APIs available to get the full Hardware ID one could use to build a more convenient front-end with the new HTTP-based API I designed for the service.

**Comment by JoshWobbles** [comment]
For example yours;
`HID\{00001124-0000-1000-8000-00805f9b34fb}_VID&0002054c_PID&05c4`
Mine;
`HID{00001124-0000-1000-8000-00805f9b34fb}_VID&0002054c_PID&05c4`

Notice for whatever reason, your setup has a spare backslash after HID, not sure why the difference.

**Comment by nefarius** [comment]
Is that what you get via device manager? This shouldn't be a valid pattern since the backslash is necessary to build the "nodes" properly.

**Comment by JoshWobbles** [comment]
I directly copied and pasted mine

**Comment by nefarius** [comment]
Odd, erm, screenshot? 😉

**Comment by JoshWobbles** [comment]
like I said, I borked my dongle lol, PC does not even pick it up any more

**Comment by nefarius** [comment]
Ah yeah, sorry, forgot that. Not to discredit you but the string isn't valid without the backslash so I'm confident why it didn't work.

**Comment by JoshWobbles** [comment]
ill get off my lazy ass and get a new one tho ;-) curious to see if that slash is the cause of my issues. But I just copied and pasted everything out of my dev manager into the reg, then copied and pasted what was in the reg into here when it didn't work.

**Comment by nefarius** [comment]
I'm awaiting your feedback, till then I consider this semi-resolved 😉
