### ISSUE TITLE
HidGuardian Whitelisting Service will not start

### ISSUE THREAD

**Issue by JoshWobbles** [nefarius/ViGEm#18]
Specifically it starts then immediately stops with the message:

> The HidGuardian Whitelisting Service on Local Computer started and then stopped. Some services stop automatically if they are not in use by other services or programs

Also, a verbose logging switch on the service exec would be helpful for debugging instances such as this.

**Comment by nefarius** [comment]
![Disclaimer](http://nefarius.at/public/Alpha-Disclaimer.png)

😉

**Comment by charlesmilette** [comment]
If we do nothing, it'll never disappear ;)

**Comment by JoshWobbles** [comment]
Just figured id report it, got it to work in a vbox tho.

**Comment by nefarius** [comment]
Just one guy, with nothing more than a few hours coding and research time per day or even week 😉 Just to keep in mind. I appreciate all the feedback but please bear in mind that most user-mode parts are nothing more than prove-of-concept yet.

**Comment by JoshWobbles** [comment]
I hear ya, i'm not jumping on you, just putting the code through its paces in the limited time that i get myself.

**Comment by Alia5** [comment]
It works fine here, if registered as service.

**Comment by nefarius** [comment]
Shall we still keep this open? The service has had a complete makeover so much less problems to be expected 😉

**Comment by JoshWobbles** [comment]
I havent tried the new service, but lets assume its fixed
