### ISSUE TITLE
Picking controller to emulate?

### ISSUE THREAD

**Issue by Blackbird88** [nefarius/ViGEm#19]
You state [here](https://github.com/nefarius/ViGEm/tree/master/ViGEmBus)  that VIGEm supports emulating these particular controllers. but how exactly do you select the one you want to emulate?
I noticed you managed to [emulate Xbone controller](https://twitter.com/CNefarius/status/761677011781910528), but again no info how you achieved that.
Any info please?

**Comment by JoshWobbles** [comment]
It is defined in the VigemTargetType enum, so when you call vigem_target_plugin, just define the controller type as the argument, such as ViGemUm.vigem_target_plugin(VigemTargetType.XboxOneWired, ref _target);

**Comment by Blackbird88** [comment]
I am user, not programmer :D

**Comment by charlesmilette** [comment]
So how would this translate for a regular user?

**Comment by JoshWobbles** [comment]
These are libraries and drivers, not programs. In their current state they dont really do much for you unless you are willing to dive into some code as the only executibles right now are just for basic tests.

**Comment by charlesmilette** [comment]
I haven't really got time to dig in the code, but the releases are working well for me. If right now there's no way for the user to change it, it should probably be added in the future.

**Comment by Blackbird88** [comment]
Shame. Wanted to test the DS4 emulation.

**Comment by JoshWobbles** [comment]
Ive been implementing the new libraries into InputMapper, but even the version that uses that is also in alpha. There functioning implementations of this library, but nothing really solid enough to encourage people into yet as Benjamin is still actively developing stuff on his end and im desperately trying to keep up. Im not sure if Benjamin has any aspirations for a UI of his own, I haven't heard anything yet.

**Comment by nefarius** [comment]
This is a Framework, not a collection of fancy GUI tools. I provide drivers and libraries for developers and currently totally lack the time to also focus on user tools too.

**Comment by nefarius** [comment]
Closing since this isn't a real issue that's worth keeping track.
