### ISSUE TITLE
x86 release missing from latest published release.

### ISSUE THREAD

**Issue by JoshWobbles** [nefarius/ViGEm#22]
There are two x64 zip files, I assume one is a typo.

https://github.com/nefarius/ViGEm/releases/tag/v1.5.4.0

**Comment by JoshWobbles** [comment]
Just FYI to others, ViGEm_x64_Win10_Signed_1152921504626356308.zip appears to be the x86

**Comment by nefarius** [comment]
OOoooooooppss.... 😴 need more sleep... thx.

**Comment by nefarius** [comment]
Fixed, thanks for quality control 😋
