### ISSUE TITLE
Does the emulated DS4 get recognized by the Remoteplay PC app?

### ISSUE THREAD

**Issue by georgcmef** [nefarius/ViGEm#25]
Hi, I would like to see if the emulated DS4 can be used using the official Sony remoteplay app for the PC. The app only allows connected DS4 controllers to be used and using my limited programming knowledge(mostly web dev) to create something that will pickup Xinput and make it appear as a DS4 controller. I just wanted to know if anyone knows if the emulated controller will work cause this will be a long slow learning process for myself, thank you.

**Comment by JoshWobbles** [comment]
Yes it can as the ViGEm device reports as a USB connected DS4.

**Comment by georgcmef** [comment]
awesome, thank you....now to learn how drivers work lol

**Comment by JoshWobbles** [comment]
Well the driver stuff is done for you for the most part, you dont want to be fussing in driver code anyway because signing them so they will actually install on your machine is a bloody nightmare (just follow nefarius' blog). All you really need to do if going at it yourself is to write a feeder application which can be done in cpp or c# that reads data from the device you want to use and feeds the exposed interfaces in ViGEm.

**Comment by georgcmef** [comment]
great thanks for the pointers mate, thank you :) i think C# would be more my flavor.

**Comment by JoshWobbles** [comment]
It is mine too mostly because I work with it so much its a second language for me, cpp does have enticing benefits however, primarily lower latency and system overhead. But in the end hardly noticeable as InputMapper is written in c# and for most people works just fine.

**Comment by georgcmef** [comment]
If i run into performance problems i might go cpp cause every millisecond counts but I am a newbie so c# should be fine. One last Q before I am done bothering this repo lol, XInputDotNet, XNA or SliMDX for reading Xinput?

**Comment by JoshWobbles** [comment]
XNA probibly easier

**Comment by georgcmef** [comment]
Awesome you rock, thanks again.

**Comment by mirh** [comment]
If you solved your doubts.. Guess like you can close this?

**Comment by EigenFace** [comment]
I've been attempting this same thing, and wrote a feeder app from XInput --> DS4Report and fed the report to VigemUM. The only problem is my emulated DS4 is still not recognized by Remote Play. It is recognized as a controller and seems to have the correct button mapping in x360ce, but Remote Play doesn't recognize it at all.

Is there some command I need to call or some handshake that is not implemented in order for remote play to recognize an emulated ds4 as genuine?

**Comment by EigenFace** [comment]
I'm a noob at all this stuff so excuse my ignorance but...
I sniffed the traffic to the PS4 with an actual DS4 when using remote play. Seems like there are some messages that are always the same(?!) that are exchanged between the controller and the PC when you start up remote play. 

It asks for a string, the controller responds with Sony Computer Entertainment, asks for another string, responds with Wireless Controller etc. There are a few other requests and responses that don't involve strings, but again the controller always seems to respond with the same data each time you start up remote play. I tried it a few times with a few hours inbetween each attempt.

So, not knowing anything and just looking at it like a black box, my idea was to sniff the traffic that the emulated ds4 sends to try to grasp exactly what exchange it's doing and what it needs to do differently to truly emulate a DS4. Only problem is i'm not sure how to sniff the traffic on the Vigem bus. 

Anyone who isn't completely ignorant of the inner-workings of the DS4 care to kindly point me in a direction I can go to try to make things work? Am I totally off-track? Is there any way I can set the proper properties or whatever of the emulated DS4 so it responds properly to the requests from remote play?

**Comment by mirh** [comment]
Cool finding. 
Given plain DS4 isn't XInput though, I'd roughly assume this bug to be [FireShock](https://github.com/nefarius/FireShock) specific. 
Maybe you might want to report this bug there.

**Comment by JoshWobbles** [comment]
Unless something has changed, i could have sworn vigem used to work in remote play.

**Comment by EigenFace** [comment]
I am not using Fireshock, I modified x360ce2Vigem to translate the XInput it outputs to a DS4 report. There could easily be an error in something I wrote I suppose, here is the gist: https://gist.github.com/EigenFace/74b56efe33eb6585e1b6384d09c4034b

**Comment by nefarius** [comment]
I wasn't touching the DS4 emulation code in month, I swear 😆

**Comment by nefarius** [comment]
@EigenFace try removing [these](https://gist.github.com/EigenFace/74b56efe33eb6585e1b6384d09c4034b#file-gistfile1-txt-L146) [lines](https://gist.github.com/EigenFace/74b56efe33eb6585e1b6384d09c4034b#file-gistfile1-txt-L147), maybe the Sony application expects the real hardware ID.

**Comment by EigenFace** [comment]
@nefarius Yatta! That did it, thank you so much. You are all gods among mortals, according to this mortal. Thank you all for your patience and help.

**Comment by nefarius** [comment]
![image](https://cloud.githubusercontent.com/assets/286631/25559342/4c6121f6-2d38-11e7-84f7-c65ad5ea1b84.png)

**Comment by georgcmef** [comment]
man, I go on vacation and this happens, good job @EigenFace and @nefarius you guys are the real mvps.

**Comment by georgcmef** [comment]
@EigenFace sorry for the necro-bump, life has gotten the way and I have done little to where I left off. Have you made any more breakthroughs? could you share the binary so i can give it a whirl? thanks in advance.
