### ISSUE TITLE
BSOD with latest x64 release

### ISSUE THREAD

**Issue by Evengard** [nefarius/ViGEm#26]
I've got a BSOD while testing the latest release with the ViGEmTester.exe (the latter compiled from latest github).

When it was writing "Starting..." and just a I hear the sound of a connected device, a BSOD occurs (retried several times, always same result).

Attaching the minidump from the crash. Hope it will be useful.

[031517-7765-01.zip](https://github.com/nefarius/ViGEm/files/842940/031517-7765-01.zip)

**Comment by nefarius** [comment]
What is "latest"? Please always include the version numbers.

**Comment by Evengard** [comment]
"Latest" was 1.5.6.0. Will test 1.5.8.0 ASAP.

**Comment by nefarius** [comment]
Outdated issue, closing.
