### ISSUE TITLE
HidGuardian does not work on the latest insider build

### ISSUE THREAD

**Issue by charlesmilette** [nefarius/ViGEm#28]
I have made sure to install and configure it properly multiple times, yet the original controller still shows up in the controller settings:

![image](https://cdn.discordapp.com/attachments/198170523954446336/295320390102679553/unknown.png)

**Comment by nefarius** [comment]
What is the latest insider build? Version information please.

**Comment by charlesmilette** [comment]
Build 15063, the RTM build for the Creator's Update.
HidGuardian is at the latest tag.

**Comment by nefarius** [comment]
Could you paste or screenshot the `AffectedDevices` registry value please?

**Comment by charlesmilette** [comment]
```regedit
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\HidGuardian\Parameters]
"AffectedDevices"=hex(7):48,00,49,00,44,00,5c,00,56,00,49,00,44,00,5f,00,30,00,\
  35,00,34,00,43,00,26,00,50,00,49,00,44,00,5f,00,30,00,32,00,36,00,38,00,00,\
  00,00,00
```

Literal value is `HID\VID_054C&PID_0268`

**Comment by charlesmilette** [comment]
I tried adding a random HID controller reported by the driver manager, no luck
This is the current value of `AffectedDevices`:

    HID\VID_054C&PID_0268
    HID\VID_045E&PID_028E&IG_00

**Comment by charlesmilette** [comment]
![image](https://user-images.githubusercontent.com/6440374/29377355-97c16614-8289-11e7-8a65-37112de8db44.png)
It broke again

Current slow ring Insider Build is 16251
Current HidGuardian version is 1.10.2.0
