### ISSUE TITLE
Build help for HidCerberus.Lib

### ISSUE THREAD

**Issue by georgcmef** [nefarius/ViGEm#29]
Hello, I know this might be a newbie question and I tried to resolve it myself(spent the last 2 days trying to fix it) I am getting a build error on HidCerberus.Lib and this is the error. 

`
ERROR
Microsoft.Build.Utilities.ToolLocationHelper could not find ildasm.exe.	HidCerberus.Lib

OUTPUT
D:\Users\XXXXXX\Downloads\ViGEm-master\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error : Microsoft.Build.Utilities.ToolLocationHelper could not find ildasm.exe			
`

I checked the Nuget packages.

`  <package id="Costura.Fody" version="1.3.3.0" targetFramework="net40" developmentDependency="true" />
  <package id="Fody" version="1.29.4" targetFramework="net40" developmentDependency="true" />
  <package id="log4net" version="2.0.5" targetFramework="net40" />
  <package id="UnmanagedExports" version="1.2.7" targetFramework="net40" />`

ildasm.exe is located in 

`C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\(NETFX 4.6.1 Tools & NETFX 4.6.2 Tools)`

Only help i seem to find on google is to reinstall UnmanagedExports. I have done that and still get the build error.

Edit: I am using VS2017

**Comment by JoshWobbles** [comment]
The path seems correct, I am posting my paths just for verification;

C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.2 Tools
C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.2 Tools\x64
C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools
C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64

So my guess is `Microsoft.Build.Utilities.ToolLocationHelper` is throwing a bad path. Try reinstalling VS and the SDK and driver toolkits.

**Comment by georgcmef** [comment]
I was hoping to avoid a reinstall (Download Cap) but that fixed the build errors thank you. 

However the reason I was interested in fixing the build error was cause I wanted to use the Tester.net application, and I was getting a runtime error and though fixing the build error would fix it. 

I still get the runtime error:

`System.ServiceModel.EndpointNotFoundException occurred
  HResult=0x80131501
  Message=Could not connect to net.tcp://localhost:26762/HidCerberusService. The connection attempt lasted for a time span of 00:00:02.0029214. TCP error code 10061: No connection could be made because the target machine actively refused it 127.0.0.1:26762. 
  Source=mscorlib
  StackTrace:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at HidCerberus.Lib.IHidCerberusWcf.HidAddPid(Int32 id)
   at HidCerberus.Lib.HidCerberus.HidGuardianOpen() in D:\Users\George\Downloads\ViGEm-master\HidCerberus.Lib\HidCerberus.Exports.cs:line 14
   at ViGEmTester.NET.Program.Main(String[] args) in D:\Users\George\Downloads\ViGEm-master\ViGEmTester.NET\Program.cs:line 10

Inner Exception 1:
SocketException: No connection could be made because the target machine actively refused it
`

The debugger says that its coming from HideCerberus.Exports.cs line 14

Once again Thank you  for all your help.

**Comment by JoshWobbles** [comment]
Is the service installed and running?

**Comment by georgcmef** [comment]
Ugh lol installed but never started cause I didn't restart or manually start it, I feel dumb. Thank you. 

Its like a never ending wack a mole, so I started the tester.net.exe.  It complained about no VigemUM.dll so i compiled it and put it in the same tester.net.exe folder. Now i get this error.

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Nefarius.ViGEm.ViGEmTarget' threw an exception. ---> System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at Nefarius.ViGEm.ViGemUm.vigem_init()
   at Nefarius.ViGEm.ViGEmTarget..cctor() in D:\Users\George\Downloads\ViGEm-master\ViGEmUM.NET\ViGEmTarget.cs:line 11
   --- End of inner exception stack trace ---
   at Nefarius.ViGEm.ViGEmTarget..ctor()
   at Nefarius.ViGEm.Targets.Xbox360Controller..ctor()
   at ViGEmTester.NET.Program.Main(String[] args) in D:\Users\George\Downloads\ViGEm-master\ViGEmTester.NET\Program.cs:line 12
```

**Comment by JoshWobbles** [comment]
I believe the libraries should be compiled platform independent (Any CPU)

**Comment by JoshWobbles** [comment]
Also, I am not entirely sure the test application here is current, I think it was just for early testing and may since be defunct.

**Comment by georgcmef** [comment]
oh...got you. I was hoping to use it to help me learn, but if not I guess I will try and find another way. I thank you for all your help once again

**Comment by georgcmef** [comment]
I have a question to your last statement. Would that also mean that the .net wrapper is also out of date(VIGEUM.NET)?

**Comment by JoshWobbles** [comment]
Not sure, ive been working mainly with one of the older releases.

**Comment by georgcmef** [comment]
Ok , I might do the same for stability and to be able to use the wrapper/tester. You have a recommended release or commit?

**Comment by georgcmef** [comment]
So I went back through the versions all the way to 1.0.0.0 and I am still getting this error:

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Nefarius.ViGEm.ViGEmTarget' threw an exception. ---> System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at Nefarius.ViGEm.ViGemUm.vigem_init()
   at Nefarius.ViGEm.ViGEmTarget..cctor() in D:\Users\George\Downloads\ViGEm-master\ViGEmUM.NET\ViGEmTarget.cs:line 11
   --- End of inner exception stack trace ---
   at Nefarius.ViGEm.ViGEmTarget..ctor()
   at Nefarius.ViGEm.Targets.Xbox360Controller..ctor()
   at ViGEmTester.NET.Program.Main(String[] args) in D:\Users\George\Downloads\ViGEm-master\ViGEmTester.NET\Program.cs:line 10
```

may I ask what version of VS you are using? I am on 2017 and maybe the problem arises when i change the toolset from 2015 to 2017?

**Comment by nefarius** [comment]
@georgcmef the exceptions means you're mixing x64 and x86 libraries/processes. Don't build with `Any CPU`, that won't work.

PS: brave to dig into this mess 😆

**Comment by nefarius** [comment]
Heya. Hopefully @georgcmef has survived my code. [I've added build instructions now](https://github.com/nefarius/ViGEm/tree/master/HidCerberus.Lib#how-to-build). Feedback welcome as always.

**Comment by georgcmef** [comment]
@nefarius awesome, I'll see if i can get it to work now. Thanks :)

**Comment by nefarius** [comment]
@georgcmef you'll also need the latest service build to ensure compatibility.

**Comment by georgcmef** [comment]
@nefarius By service build do your mean VS2015 or PocoLibraries?. Cause respectively they are 2015 Update 3 and 1.7.8p2. Cause of course for me I am getting errors. I followed the step by step for building in the read me and I get some 140 errors. 

```
Downloaded POCO
UNZIPPED: to D:/Downloads
OPENED: vs2015 Native x86 command
COPIED/PASTED: %comspec% /k ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"" x86
NAVIGATED CMD TO: D:/Downloads/poco-1.7.8p2
COPIED/PASTED: buildwin 140 build static_mt both Win32 nosamples
DID THE SAME FOR: x64, but changed strings copied/pasted and cmd prompt
OPENED PROPERTY MANAGER IN VS2015: added macro POCO_ROOT with D:/Downloads/poco-1.7.8p2 to both debug x86 and x64
```
now i get 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MDd_DynamicDebug' in dllmain.obj	HidCerberus.Lib	D:\Users\George\Downloads\ViGEm-master\HidCerberus.Lib\pocofoundationmt.lib(Windows1250Encoding.obj)	1	
```
X140 with some variation and this single error

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'PocoFoundationd.lib'	HidCerberus.Lib	D:\Users\George\Downloads\ViGEm-master\HidCerberus.Lib\LINK	1	
```
I am getting very discouraged, I have put in 20+ hours and yet to write a single line of code.

**Comment by nefarius** [comment]
@georgcmef ne, i meant the `HidCerberus Service` but never mind.

What's the value of `Runtime Library` in your project?

![image](https://cloud.githubusercontent.com/assets/286631/25591105/90bc8648-2eb3-11e7-817f-6f7c5e914258.png)

**Comment by georgcmef** [comment]
@nefarius It is "Multi-threaded Debug DLL (/MDd)" I will change that to what you have.

**Comment by nefarius** [comment]
@georgcmef no, don't do that, I've found the error. Fixing right now.

**Comment by nefarius** [comment]
@georgcmef it's fixed now, I forgot to configure the projects Debug settings since I almost never use debug builds. Pull the latest changes and you should be fine.

**Comment by georgcmef** [comment]
Ok, trying it now. Thanks for your help.  :)

**Comment by nefarius** [comment]
Np, I know getting used to static vs. dynamic linking and 3rd party libraries takes some time and can be confusing as well.

**Comment by nefarius** [comment]
Is this still an issue?
