### ISSUE TITLE
HidCerberus.Lib will not build due to Fody

### ISSUE THREAD

**Issue by JoshWobbles** [nefarius/ViGEm#30]
Apparently Fody became incompatible at some point along the way and the project will not build with the used version.

Initial error prior to Fody update:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error		Fody: An unhandled exception occurred:
> Exception:
> Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
> StackTrace:
> 
> Server stack trace: 
>    at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
>    at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
>    at System.Reflection.RuntimeMethodInfo.GetParameters()
>    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
> 
> Exception rethrown at [0]: 
>    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
>    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
>    at IInnerWeaver.set_Logger(ILogger value)
>    at Processor.ExecuteInOwnAppDomain() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\Fody\Processor.cs:line 146
>    at Processor.Inner() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\Fody\Processor.cs:line 93
>    at Processor.Execute() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\Fody\Processor.cs:line 45
> Source:
> mscorlib
> TargetSite:
> Void GetSignature(Void*, Int32, System.RuntimeFieldHandleInternal, System.IRuntimeMethodInfo, System.RuntimeType)
> Could not load file or assembly 'Microsoft.Build.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
> StackTrace:	HidCerberus.Lib

**Comment by nefarius** [comment]
It should work now, could you please verify?

**Comment by JoshWobbles** [comment]
I do believe the Fody issue is resolved, I saw a push that had the new version so that should fix it, though since I wrote my own service have not had a chance to try yours again.

**Comment by nefarius** [comment]
Latest library is now native C++, no more .NET code or Fody, so this issue became obsolet.
