### ISSUE TITLE
HidCerberus Build service starter into library.

### ISSUE THREAD

**Issue by JoshWobbles** [nefarius/ViGEm#31]
In response to https://github.com/nefarius/ViGEm/issues/29#issuecomment-291219696 where the script threw an error due to the service not running, perhaps the library should attempt to start the service if it isn't already.

**Comment by nefarius** [comment]
This would only work if the process calling it has elevated rights and I'm all for solutions that don't require administrative rights. Service startup should be handled by an installer, not by the calling process.

**Comment by JoshWobbles** [comment]
Yea, in my service I did just that, built it into the services installer (Not the windows installer), it limited the number of dumb dumb mistakes on my part.

**Comment by nefarius** [comment]
I redesigned the service to use [Topshelf](http://topshelf-project.com/); you can now self-register the binary as service via `HidCerberus.Srv.exe install` in an elevated prompt. Or run it standalone for testing.
