### ISSUE TITLE
System.BadImageFormatException

### ISSUE THREAD

**Issue by JoshWobbles** [nefarius/ViGEm#32]
Been getting this for a while, compiling HidCerberus.Lib.dll as x64 and it still says its invalid. Is the library only x86?

> 18:42:32,668 [MyShock] ERROR - Error:
> System.BadImageFormatException: Could not load file or assembly 'file:///C:\Users\jhebb\Documents\Visual Studio 2015\Projects\InputMapper1\InputMapper1\bin\Release\HidGuardian\x64\HidCerberus.Lib.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format.
> File name: 'file:///C:\Users\jhebb\Documents\Visual Studio 2015\Projects\InputMapper1\InputMapper1\bin\Release\HidGuardian\x64\HidCerberus.Lib.dll'
>    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean System.Windows.Data Error: 12 : TargetNullValue 'False' (type 'String') cannot be converted for use in 'Visibility' (type 'Visibility'). BindingExpression:Path=MainFrameCollapsed; DataItem=null; target element is 'TabControl' (Name='MainTabNav'); target property is 'Visibility' (type 'Visibility') FormatException:'System.FormatException: False is not a valid value for Visibility. ---> System.ArgumentException: Requested value 'False' was not found.
>    at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
>    at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
>    at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
>    at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
>    --- End of inner exception stack trace ---

**Comment by JoshWobbles** [comment]
> === Pre-bind state information ===
> LOG: Where-ref bind. Location = C:\Users\jhebb\Documents\Visual Studio 2015\Projects\InputMapper1\InputMapper1\bin\Release\HidGuardian\x64\HidCerberus.Lib.dll
> LOG: Appbase = file:///C:/Users/jhebb/Documents/Visual Studio 2015/Projects/InputMapper1/InputMapper1/bin/Release/
> LOG: Initial PrivatePath = NULL
> Calling assembly : (Unknown).
> ===
> LOG: This bind starts in LoadFrom load context.
> WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
> LOG: Using application configuration file: C:\Users\jhebb\Documents\Visual Studio 2015\Projects\InputMapper1\InputMapper1\bin\Release\InputMapper1.exe.Config
> LOG: Using host configuration file: 
> LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
> LOG: Attempting download of new URL file:///C:/Users/jhebb/Documents/Visual Studio 2015/Projects/InputMapper1/InputMapper1/bin/Release/HidGuardian/x64/HidCerberus.Lib.dll.
> ERR: Failed to complete setup of assembly (hr = 0x8007000b). Probing terminated.

**Comment by JoshWobbles** [comment]
Tried a new WPF app just to eliminate possible issues in my own, and on a 4.5.2 targeted WPF application I get the same issue when just doing somthing as simple as:

```
namespace HidGuardianTestApp
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            HidCerberus.Lib.HidCerberus.HidGuardianOpen();
        }

        private void Window_Closing(object sender, System.ComponentModel.CancelEventArgs e)
        {
            HidCerberus.Lib.HidCerberus.HidGuardianClose();
        }
    }
}
```

**Comment by nefarius** [comment]
I recently (~last two days) did a complete re-design of the service/library combo; the library is now a native C++ library without DllExport-trickery available for `x86` and `amd64`. It still lacks the documentation, I'll work on that next.
