### ISSUE TITLE
Bluetooth capabilities in the future?

### ISSUE THREAD

**Issue by Alpharou** [nefarius/ViGEm#34]
Just to know, will it be bluetooth dongle hosting like in the SCP Toolkit project? It's not a must have feature because of the input lag, but oh it is AWESOME to plop one inexpensive dedicated bluetooth usb and use the controller from the couch...

**Comment by charlesmilette** [comment]
Fireshock works on ps4 controllers connected via Bluetooth

**Comment by JoshWobbles** [comment]
Did you mean to post this in the fireshock project? ViGEm is a device emulator, no BT or USB involved in this end.

**Comment by Alpharou** [comment]
o.O Oh sorry. xD
