### ISSUE TITLE
Understanding ViGEm

### ISSUE THREAD

**Issue by Vebryn** [nefarius/ViGEm#37]
Hi,

I'm a little bit confused about ViGEm. I understand that FireShock is a native driver for DS. My DS3 gets successfully installed with this driver. I understand that we can add XInput support with ViGEm if we set UseViGEm to 1 in Registry.

> If a DualShock 4 gets connected, it enables XInput-Support if ViGEm is installed. Same goes for a DualShock 3.

ViGEm is provided with 3 drivers : vigembus, hidguardian and xnaguardian. What are porpose of these drivers ? I read README of each project. No one talks about XInput for my DS3. Which one have I to install ? What are differences between **right-click > install** on inf files and using devcon commands ?

Nice project!

Best regards.

**Comment by charlesmilette** [comment]
ViGEm bus emulates a Xbox 360 controller and as such adds support for
Xinput.
XnaGuardian just adds additional feature to Xinput, you can ignore this.
HidGuardian allows you to hide the FireShock DirectInput controller so that
applications only sees the Xinput controller and prevent double input.

You need the devcon command to install the driver, it doesn't works with
right-click and install because you won't have the class filters. Devcon is
included in the windows 10 sdk.

**Comment by Vebryn** [comment]
Thank you for the explanation. I firstly plug my DS3. FireShock driver was used. Next, I use devcon to install both drivers. I don't see any HidGuardian or ViGEm bus in device manager. Have I to see something ? How can I check if drivers are properly installed ?

**Comment by Oceangraves** [comment]
I'm not really 100% sure on what to do either, but with some google-fu I grabbed the devcon.exe placed it in my system path and now tried this command:

devcon install F:\ViGEm_signed_Win7-10_x86_x64\drivers\x64\ViGEmBus.inf {4D36E97D-E325-11CE-BFC1-08002BE10318}

That command was found here: https://docs.microsoft.com/en-us/windows-hardware/drivers/install/using-the-devcon-tool-to-install-a-driver-package

Unsure what the \mstoaster is for

**Comment by JoshWobbles** [comment]
See https://github.com/charlesmilette/ViGEm/blob/52afad5dfae2bb51cf3dfe58601d7b14caa6c178/ViGEmBus/README.md

**Comment by charlesmilette** [comment]
yeah I pr'ed that because I had to dig through the installer's source
to find it since the latest version doesn't have one.

**Comment by Oceangraves** [comment]
Ah I didn't notice there was a readme (none in the zip and usually github projects have the instructions in the main project page. I was close but no cigar, works now! Thanks for the quick reply by the way.

**Comment by nefarius** [comment]
I take this as a hint to focus documentation next 😆

**Comment by psyke83** [comment]
Are there known issues with Insider builds? I'm running Windows 10 x64 build 16232 - the ViGemBus is installed using the proper instructions at: https://github.com/nefarius/ViGEm/tree/master/ViGEmBus - 

There was no error during driver installation but no emulated pad is enumerated when I connect my DS3. I also installed HidGuardian and rebooted, but still no luck.

**Comment by JoshWobbles** [comment]
@psyke83 And you have fireshock installed?

**Comment by psyke83** [comment]
Yes, FireShock v1.3.1.0 and it's working (same as @Vebryn's screenshots above).

Hmm, I may have installed Fireshock prior to updating to the new build and something didn't carry over properly. I'll try uninstalling everything and re-install to be sure.

I've also got an ScpVBus driver installed; it's not from @nefarius's ScpToolkit, but from the parsec.tv software (for game streaming to raspberry pi). I'll get rid of that just in case.

**Comment by JoshWobbles** [comment]
Would also be helpful to know your ViGEm version, and should probibly uninstall HidGuardian for the time being just to make sure that it isnt misconfigured as a point of failure.

**Comment by psyke83** [comment]
Whoops, meant to specify in the first post. It's the latest version, ViGEm v1.10.0.0. I've also got SecureBoot disabled, so I'm pretty sure it's not a driver signing issue (but I see that these drivers are not validated). I'll uninstall everything and try again.

**Comment by JoshWobbles** [comment]
The drivers work fin under secure boot as they are signed. did you make sure the DS3 is using the fireshock driver in dev manager?

**Comment by psyke83** [comment]
As I said, the DS3 was working using Fireshock. It was

**Comment by ReTheOff** [comment]
Just curious, does hdwwiz (Add Hardware Wizard) work for installing ViGEm drivers too?  I tried, seems to load devices into Device Manager ok.    Also, are the .sys and .dll's supposed to end up in system32 directory if they are x64?  (seen in driver details in device mangager)   FYI, controller is not working for me, which is why I'm asking. This was an upgrade from versions a few months back.

**Comment by JoshWobbles** [comment]
@ReTheOff Instructions for installation are in the readme https://github.com/nefarius/ViGEm/blob/master/ViGEmBus/README.md

**Comment by ReTheOff** [comment]
Thanks @JoshWobbles , I'll get devcon and install per instructions.  However, is hdwwiz not performing the same task?

**Comment by nefarius** [comment]
Since this "issue" is all over the place; closed :P
