### ISSUE TITLE
Init error: 536870912

### ISSUE THREAD

**Issue by JoshWobbles** [nefarius/ViGEm#38]
Trying the new versions of the driver, both the 360 and the DS4  are returning 536870912 (0x20000000) which is well outside the VigemError enum, when ViGemUm.vigem_init(); is called. Does this point to anything specific?

**Comment by JoshWobbles** [comment]
As a double-check, the ViGEm bus is installed and reporting to windows that it is running fine.

**Comment by JoshWobbles** [comment]
Thought it might be somthing in my code, so I grabbed a new pull and got the same thing when running ViGEmTester.Net:
> System.TypeInitializationException occurred
>   HResult=0x80131534
>   Message=The type initializer for 'Nefarius.ViGEm.ViGEmTarget' threw an exception.
>   Source=ViGEmUM.NET
>   StackTrace:
>    at Nefarius.ViGEm.ViGEmTarget..ctor() in C:\Users\jhebb\Source\Repos\ViGEm\ViGEmUM.NET\ViGEmTarget.cs:line 21
>    at Nefarius.ViGEm.Targets.Xbox360Controller..ctor()
>    at ViGEmTester.NET.Program.Main(String[] args) in C:\Users\jhebb\Source\Repos\ViGEm\ViGEmTester.NET\Program.cs:line 12
> 
> Inner Exception 1:
> Exception: Init error: 536870912

**Comment by charlesmilette** [comment]
Could this be related to nefarius/FireShock#14?

**Comment by JoshWobbles** [comment]
Doubt it, that issue just says the controls wont work (suggesting that bus init's and the device adds, just is not getting communication. In my instance the bus will not even initialize.

**Comment by JoshWobbles** [comment]
Take that back, its possible. Are you able to run the UM.Net example?

**Comment by charlesmilette** [comment]
ViGEm/ViGEmTester.NET/Program.cs i would assume?

**Comment by JoshWobbles** [comment]
yup

**Comment by nefarius** [comment]
Ooops, that's 'cause I changed the error codes in the native library to correspond with the NT_STATUS format. I have to update the .NET wrapper accordingly. Thanks for noticing 😉

**Comment by JoshWobbles** [comment]
Don't think 0x20000000 is a NT_STATUS code either. Is it something internal?

**Comment by nefarius** [comment]
[Yes it is](https://github.com/nefarius/ViGEm/blob/master/ViGEmUM/ViGEmUM.h#L43)

**Comment by JoshWobbles** [comment]
Would you consider making the no error/success 0x00000000?

**Comment by nefarius** [comment]
Nope, [see here](https://msdn.microsoft.com/en-us/library/cc231200.aspx)

**Comment by JoshWobbles** [comment]
Right I would think that 0x2 would be reserved for customer "errors" since 0x0 is already STATUS_SEVERITY_SUCCESS.
