### ISSUE TITLE
Cannot create multiple callback notifications for different targets

### ISSUE THREAD

**Issue by ToadKing** [nefarius/ViGEm#41]
Repeat calls to `vigem_register_xusb_notification` (and I assume the other controller notification functions) fail if they are given an identical callback function but different target. This makes it impossible to have multiple callbacks for multiple controllers.

**Comment by nefarius** [comment]
Yupp, my bad, that's an idiotic bug; I have to keep track of the function pointers per device and not per process. Will improve this. Thanks for reporting.
