### ISSUE TITLE
ViGEmBus can't create devices after destorying previous ones in some situations

### ISSUE THREAD

**Issue by ToadKing** [nefarius/ViGEm#42]
I've ran into an issue where creating a virtual Xbox 360 controller, deleting it, then creating a new one, the 360 driver fails to load on the second device:

> Windows cannot load the device driver for this hardware because a previous instance of the device driver is still in memory. (Code 38)
>
> The driver could not be loaded because a previous version of the driver is still in memory.

I've encountered this with my Switch Pro controller driver project: https://github.com/ToadKing/switch-pro-x

The latest version of the project communicates with the controller through the Windows HID driver but a previous version that assigned the device to a WinUSB driver and used libusb does not exhibit this issue.

**Comment by ToadKing** [comment]
I'm using the latest release of drivers, and using ViGEmBus in combination with HidGuardian.

OS: Windows 10 Pro x64 10.0.15063

**Comment by Alia5** [comment]
I'm facing the same issue using the latest release of the ViGEmBus driver (only ViGEmBus) even when not deleting any previous device instance.

Win10 Pro x64 15063.413

**Comment by ToadKing** [comment]
Reverting to the bus driver in the 1.8.1.0 release fixes this issue.

**Comment by Codeusa** [comment]
This is being caused by the update that fixed #13

**Comment by nefarius** [comment]
@Codeusa @ToadKing bloody hell, you have to be kidding me 🤣 but at least we have a clue, thank you. I will look into this ASAP (which by my time standards is... soon 😉 )
