### ISSUE TITLE
Issues building ViGEmuM with x64 target

### ISSUE THREAD

**Issue by Codeusa** [nefarius/ViGEm#43]
I'm attempting to build the ViGEmuM driver and c++ library with a x64 target. However I'm running into some errors. I've attached the logs below.

I'm running Windows 10 with the latest Windows SDK installed and the latest Windows Driver Kit. Win32 builds fine so I'm not sure what might be misconfigured in my environment or if the project might have an issue. 

[Debug.zip](https://github.com/nefarius/ViGEm/files/1117832/Debug.zip)

**Comment by ToadKing** [comment]
I've found that upgrading Windows SDK and WDK packages can often times lead to bad installs. I was having issues as well until I uninstalled every previous Windows SDK/WDK and then installing only the latest versions.

Also I got it to work using VS 2015 so other versions (2013/2017) might not work.

**Comment by Codeusa** [comment]
@ToadKing that did it. Thanks.
