### ISSUE TITLE
ViGEmBus - Bad XInputGetCapabilities returned

### ISSUE THREAD

**Issue by ToadKing** [nefarius/ViGEm#44]
When calling [XInputGetCapabilities](https://msdn.microsoft.com/en-us/library/windows/desktop/microsoft.directx_sdk.reference.xinputgetcapabilities(v=vs.85).aspx) on a device made with ViGEmBus, bad values for the `Gamepad` structure are returned. This is the issue in #5 since Dolphin actually uses the return values from XInputGetCapabilities to detect which buttons/triggers/axis are actually available on the device.

**Comment by nefarius** [comment]
To be honest I never tested `ViGEm` with this function (note: expand test matrix), can you tell me what you get returned? Random garbage? Always the same data?

**Comment by ToadKing** [comment]
It appears to be random, but it only calculated once upon device creation. Repeat XInputGetCapabilities calls on the same instance return the same values. It also always seems to return 0 for LY/RX/RY sticks, but random data for LX.

![Example 1](https://i.imgur.com/Y63RXdg.png)

![Example 2](https://i.imgur.com/UEf0v7I.png)

**Comment by nefarius** [comment]
![image](https://user-images.githubusercontent.com/286631/27841082-ae6a9130-60fe-11e7-8bf5-7c69bf3a17b8.png)

**Comment by tpill90** [comment]
I am also able to reproduce this in Dolphin.  ViGEm works fine in most other applications, but button presses only register randomly in Dolphin.

@nefarius I have some time that I can spend trying to fix this bug, however I have zero experience with working on drivers.  I've been familiarizing myself with this codebase, and I'm pretty overwhelmed with where to start.  Any ideas on where to start looking to resolve this issue, or any documentation that could help w\ this issue?

**Comment by nefarius** [comment]
Hey @tpill90 thanks for the offer!

Do you have experience with IDA or reversing/disassembly in general? Wireshark/USBpcap? I have a few ideas but I'm afraid the solution doesn't solely lie within the code but the while driver stack. Just drop me a note if you want to talk in private about this.

**Comment by tpill90** [comment]
@nefarius Will do.  Maybe sometime next week we can go over this.  Thanks!

**Comment by nefarius** [comment]
I still have no goddamn idea why this happens 😠

**Comment by Manlibear** [comment]
I'm also having similar issues, is there any information I can give that might help get a better picture of things?

I'm using ViGEmu in the context of Parsec streaming. Laptop with a Gamesir G3w (xinput) connected streaming from a PC, both Windows 10 Fall Creators.

**Comment by Zenexer** [comment]
Able to reproduce with Parsec + Xbox 360 Rock Candy controller.

**Comment by Zenexer** [comment]
@ToadKing Does https://github.com/dolphin-emu/dolphin/commit/4fb2d1e361823667c261333ab7eaccd8079b2459 work around this?

**Comment by nefarius** [comment]
@Manlibear IDK which call inside XInput determines these values and I don't see it on bus level so I don't know where to start troubleshooting.

**Comment by JoshWobbles** [comment]
I may be way off, but there is a device subtype that uses LX and no other stick axeses (except triggers) and that is the XINPUT_DEVSUBTYPE_WHEEL (2), perhaps your device is not identifying as XINPUT_DEVSUBTYPE_GAMEPAD (1) so some games are not treating properly?????

**Comment by nefarius** [comment]
I'll now try to look at differences between a real pad and my implementation with Wireshark.

**Comment by nefarius** [comment]
@JoshWobbles looking at the disassembly the XInput libs only cover the case of `dwFlags` being `XINPUT_FLAG_GAMEPAD` like stated on MSDN.

**Comment by nefarius** [comment]
@JoshWobbles ditch what I just said, I looked at the wrong parameter 🤣

**Comment by nefarius** [comment]
The trail suddenly got hot again:

![](https://lh3.googleusercontent.com/-7RXvqEwDlw0/Wlt71k-sSRI/AAAAAAAAAs0/s9VFGBWM4cE2X91_ISa3-5F3l6hKGn1zQCHMYCw/s0/2018-01-14_16-48-41.png)

**Comment by nefarius** [comment]
*Scarlet.Crush* y u lie to me?!

![](https://lh3.googleusercontent.com/-lnpBkApNbZ8/Wlt86jh9BOI/AAAAAAAAAtA/6H0gAHdFMiIXTlflxSG3H2GozznfaaFowCHMYCw/s0/devenv_2018-01-14_16-53-16.png)

**Comment by nefarius** [comment]
Uuuuhhh.... I fixed it 😲 

![](https://lh3.googleusercontent.com/-Rh5FREQs1Mk/WluvCFShE_I/AAAAAAAAAtQ/eXF_Oybu9q4cgoNYqKWm-E-9WSadNwYhACHMYCw/s0/vmware_2018-01-14_20-27-01.png)

**Comment by nefarius** [comment]
[Demovideo](https://mega.nz/#!K9tVUZbC!jc7Tg4VOCDDk9arvkvYmm0z6TH4jjS0bkcM6aw8gF9Y) up, binaries come next.
