### ISSUE TITLE
Problems trying to install ViGEm Bus Driver

### ISSUE THREAD

**Issue by uanacho** [nefarius/ViGEm#46]
Hi, I'm trying to install ViGEm Bus Driver.
I'm following the instructions of "Manual Installation" and I executed
`devcon.exe install ViGEmBus.inf Root\ViGEmBus`
First of all the devcon executable which I had was in C:\Program Files (x86)\Intel\Bluetooth\utilities
I opened the cmd with administrator rights and the installation failed.
Then I tried with different devcon executables that came with WDK 10 (Windows Driver Kit)
and it failed too.
I'll give you a screenshot.
Am I wrong or is missing something?
Thanks
![captura](https://user-images.githubusercontent.com/11463553/27880256-bbc17366-619a-11e7-9849-0ab5f7df4416.png)

**Comment by ToadKing** [comment]
If you are building the drivers yourself make sure you have test signing mode enabled for Windows. Otherwise, the Event Viewer should have more details on exactly why the driver didn't install.

**Comment by nefarius** [comment]
Heya @uanacho, it looks like you just cloned the repo and try to install the included `*.inf` but sadly it's not that easy; you need the compiled and signed driver files. [I provide built ones in the release tab](https://github.com/nefarius/ViGEm/releases).

**Comment by uanacho** [comment]
Oh, 
Yes I did what you said @nefarius 
I'll give it a try.
I didn't understand that I have to sign the driver files.

**Comment by JoshWobbles** [comment]
Don't think you can self sign in Windows 10 anymore either unless you jump through a hoop on each boot-up.

**Comment by nefarius** [comment]
I'm a bad example there since I'm working with an upgraded installation.

**Comment by uanacho** [comment]
I finally could install the driver using the "signed version" as you suggested.
Thanks!
