### ISSUE TITLE
HidGuardian does not properly hide XB360 controllers

### ISSUE THREAD

**Issue by evilC** [nefarius/ViGEm#47]
HidGuardian (using v1.10.1.0 release) can hide my DirectInput devices just fine, but for my XB360 controller, although it removes it from joy.cpl, applications can still see it.  
I have the following in AffectedDevices (HC seems to insert 00, device manager says 01, I have tried both in isolation too):
```
HID\VID_045E&PID_028E&IG_00
HID\VID_045E&PID_028E&IG_01
```
![](http://i.imgur.com/patxWNf.gif)

**Comment by nefarius** [comment]
This is perfectly normal, the XInput APIs don't use the HIDUSB stack so they are not affected by HidGuardian.

**Comment by evilC** [comment]
So HidGuardian is of no use for XInput controllers? What a major bummer...  
You may wanna remove mention of XInput from the [HidGuardian page](https://github.com/nefarius/ViGEm/tree/master/HidGuardian) then, as it seems to imply that HG will work for XInput, whereas it now appears that this is a DirectInput-only solution.

**Comment by JoshWobbles** [comment]
@evilC Its a HID solution, hence the name, It just so happens that DI devices usually implements the HID class. The only mention of XInput is when giving an example of device APIs. But this is neither DirectInput nor XInput, for example this could block keyboards, mice, barcode readers, and various other input devices that do not implement DirectInput APIs.

**Comment by evilC** [comment]
HG cannot block mice or keyboards, Nefarius has previously confirmed this, and this is borne out by my testing.

**Comment by nefarius** [comment]
That's why I don't like mentioning DirectInput; it's an abstraction API and has in fact nothing to do with device drivers. It just happens to provide access to a majority of devices because they are HID compliant. The Xbox peripherals are **not** HID compliant, thus I refer to them as XUSB/XGIP devices.

**Comment by nefarius** [comment]
@evilC it can but at API level, not OS level. That's why I listed the APIs in the Readme. Windows itself doesn't access mice via RawInput so they won't geht hidden.

**Comment by evilC** [comment]
Is it technically feasible to implement something like HG for XInput devices? Or is X360ce going to be the only solution in perpetuity?

**Comment by nefarius** [comment]
I already tried this with `XnaGuardian` but due to the implementation design it's way harder to achive the same effect on XUSB and haven't had success yet.

**Comment by mirh** [comment]
I think you can already spoof/block/guard XInput devices with x360ce
