### ISSUE TITLE
ViGEm Freezes Win7 VMs

### ISSUE THREAD

**Issue by Alia5** [nefarius/ViGEm#49]
Plugging in a virtual XB360 device through the ViGEm driver, completely freezes my Win7 VMs (VMWare)

Happens with the latest version of the Driver. (1.10.2.0)
Only the ViGEmBus driver is installed

This however, works flawless on Win10 VMs

**Comment by nefarius** [comment]
Do you get a BSOD with a memory dump?

**Comment by Alia5** [comment]
Nope, just freezes the VM.
No BSODs whatsoever :/

**Comment by nefarius** [comment]
You have a physical machine for test availble?

**Comment by Alia5** [comment]
Machines, yes. But no hard drive to quickly put Win7 on.

**Comment by nefarius** [comment]
I'll test once I'm back home in a few days.

**Comment by Alia5** [comment]
Magically fixed with v1.11.1.0

**Comment by Alia5** [comment]
I guess we can close this now?
