### ISSUE TITLE
Most buttons do not function with the Dolphin Emu

### ISSUE THREAD

**Issue by XSuperMarioX** [nefarius/ViGEm#5]
## So my controller got randomly unplugged and now only D-Pad up and the left and right sticks function in dolphin.

So in another game, Pit People Beta, the R-Trigger was detected as the start button but in another it worked fine being Nep U.  Seems a little temper mental haha

**Comment by nefarius** [comment]
Sorry but what should I do with this little information; ViGEm doesn't do anything on it's own, what's the setup you're using, your system specs etc. etc.

**Comment by XSuperMarioX** [comment]
Oh I'm sorry.
CPU:  i5-4690k
GPU:  XFX R9 285
Mobo:  Asus Z97-A
Ram: 2x8GB Corsair vengence.
OS:  Windows 10 64Bit  Build 10586.494
Controller is a PS3 controller model # CECHZC2U, the plastic on the sticker came off taking the serial number with it but I bought it at Walmart years ago.

BF4 by default has all the buttons and analogue sticks in all the wrong order as well.

**Comment by nefarius** [comment]
By setup I didn't mean you PCs specs, I mean since ViGEm can't function on it's own; how are you feeding it? With FireShock?

**Comment by nefarius** [comment]
*Sigh* this leads to nothing, closing.

**Comment by Zenexer** [comment]
For people coming from Google, see #5.
