### ISSUE TITLE
Wired 360 controller analogue sticks in Parsec vs Nvidia Gamestream

### ISSUE THREAD

**Issue by stretchneck** [nefarius/ViGEm#51]
My ongoing testing of cloud gaming...

In Nvidia Gamestream the analogue sticks on a wired 360 controller are correctly calibrated, it also appears to include the initial resistance for small movements.  In Parsec using ViGEM, there is no initial resistance and the sensitivity is greatly increased, with full motion being achieved over a small area.  The wired 360 controller is calibrated on the host PC - any advice?

Host PC - Windows 10
Client PC - MacOS

**Comment by nefarius** [comment]
Uh, `ViGEm` outputs what you feed it, I don't do any dead-zone or other fancy tricks, that's the burden of the feeder developer, so I don't know if I'm at assistance here...
