### ISSUE TITLE
VDX+x360ce = PS4 remote play trigger problem.

### ISSUE THREAD

**Issue by Sawyer007** [nefarius/ViGEm#58]
My Logitech f310, configured in x360ce so all buttons and triggers work.
Tested it in win10 x64 under controllers. All looks and responds good to me.

But in the ps4 remote play app. Everything else but the left and right triggers wont respond at all.

I use this drivers https://faq.parsec.tv/articles/12905-enabling-or-fixing-controller-support

**Comment by heshamalkhiat** [comment]
Me too have the same issue with ps4 remote play app and i dont know how to fix it 
and i found this fix but i dont know how to use it !!

https://github.com/nefarius/ViGEm/commit/75933e8f0bc16be88253006061ae55c6077be323

**Comment by nefarius** [comment]
Fix is already pushed to the repo, I'll release a new build of VDX probably this weekend.

**Comment by bellero2007** [comment]
Please nefarius can you release the new build? Thank you

**Comment by nefarius** [comment]
It already is: https://downloads.vigem.org

**Comment by bellero2007** [comment]
Thank you, I didn't see it because I look the link in this page: https://github.com/nefarius/ViGEm/tree/master/Src/Samples/VDX

**Comment by nefarius** [comment]
I always a bit behind 😉

**Comment by nefarius** [comment]
I updated the README

**Comment by askewmetal** [comment]
How to simulate the touch of the touchpad?

**Comment by nefarius** [comment]
Somebody has to implement it :wink:

**Comment by mirh** [comment]
Dilemmas for free time: bigger priority for a) wiring touch system or b) porting to KMDF 

Luckily I guess it's easier not to ask such questions and just follow whatever fancy stops by.

**Comment by nefarius** [comment]
Sorry but what answer do you expect me to give, I don't hide shiny code in my basement. If it's not public I have no solution. Simple as that. Hope I could shed some light on the subject.
