### ISSUE TITLE
Double input causing conflict in certain games (e.g. Dark Souls)

### ISSUE THREAD

**Issue by psyke83** [nefarius/ViGEm#6]
Hi,

Fantastic work on ViGEm & FireShock! Unfortunately, some games conflict with this solution due to the existence of both dinput/xinput devices. In Dark Souls, buttons are not detected correctly, but if you start the game via the keyboard, the camera rotates constantly.

Here's a workaround (at least for Dark Souls):
- Download dinput8-x360cev21.zip from: https://drive.google.com/drive/folders/0B4lfqq0DpUo-SnNRRzNOa3doWjA?tid=0B4lfqq0DpUo-WGV0OVVTS1Z0LVk
- Extract the dinput8.dll from the blocker folder and extract to the Dark Souls DATA folder.
- (Optional) If using DSFix, rename dinput8.dll to something else and configure DSFix.ini to load the second dll via the dinput8dllWrapper option.

Result: Dark Souls now works perfectly.

I'm seeing the same problem in DS3 but I'm hesitant to try the blocker dll in case it triggers the anti-cheat mechanism.

Hopefully you can come up with a driver-side solution to solve this issue; perhaps you should block dinput inputs when the ViGEm driver is running?

**Comment by charlesmilette** [comment]
Another solution could be having a config option for FireShock to output XInput controls directly, or to have a kind of way for FireShock and ViGEm to communicate together and have FireShock disable the DInput controller.

**Comment by nefarius** [comment]
I'm well aware about this issue and currently investigating a proper solution.

**Comment by nefarius** [comment]
@charlesmilette the problem with your suggestion is that the interface between the XInput-DLLs and the driver isn't documented anywhere so I'm - once again - poking in the dark to reverse engineer it.

**Comment by nefarius** [comment]
![image](https://cloud.githubusercontent.com/assets/286631/20462136/9bae8f8e-af14-11e6-94f5-8559840b53dc.png)

[Fix available!](../tree/master/HidGuardian)
