### ISSUE TITLE
Signing fails on Windows 7

### ISSUE THREAD

**Issue by epigramx** [nefarius/ViGEm#61]
The drivers of the last couple of releases (at least) seem to work fine on Windows 10 on 2 different PCs. However, on Win 7 they appear unsigned (unless that Win 7 needs a Microsoft update of some sort since it's relatively barebones for virtual machine uses).

**Comment by sylveon** [comment]
Yep you're missing on an update https://github.com/nefarius/ViGEm/tree/master/Sys/ViGEmBus#necessary-preparations-for-windows-7

**Comment by epigramx** [comment]
Thank you, I forgot about that (I did notice it initially but..). Sorry for the confusion.
