### ISSUE TITLE
Is it normal that force feedback isn't provided by the emulated DS4 device?

### ISSUE THREAD

**Issue by epigramx** [nefarius/ViGEm#62]
Or do I miss an option I have to enable? XInput supports it fine apparently.

**Comment by nefarius** [comment]
It is, what makes you think otherwise?

**Comment by epigramx** [comment]
Because rumble support doesn't seem to be detected software. Do you know what's the best way to test it and show that it works?

**Comment by Alia5** [comment]
DirectInput API has no ways of doing rumble.

**Comment by nefarius** [comment]
I used DS4Windows for my tests and `ViGEm` reported rumble requests just fine. The game/process has to support it ofc.

**Comment by epigramx** [comment]
DS4Windows does indeed provide DirectInput force feedback to ViGEm. I guess most software out there does not support force feedback at all unless it's from XInput.

**Comment by epigramx** [comment]
Right, thanks for the clarification. For the record the confusion was that I expect that there was full force feedback support via the DInput device but I guess rumble is only possible via the emulated HID device.
