### ISSUE TITLE
Is it normal that reinstalling the bus driver leaves 2 hidden unused HIDs and is there a way to avoid it?

### ISSUE THREAD

**Issue by epigramx** [nefarius/ViGEm#66]
![1](https://i.imgur.com/1u26XYm.png)

Two extra "HID-compliant game controller" and "USB Input Device" entries remain hidden and unused if the bus driver is reinstalled. Otherwise it works fine. Is this normal behavior? Can it be avoided?

**Comment by nefarius** [comment]
That's a Windows "issue" since traces of emulated devices remain in the registry. I don't see that as a ViGEm issue.

**Comment by epigramx** [comment]
Is it the same process that leaves hidden devices with a re-pairing?
