### ISSUE TITLE
This device cannot start. (Code 10)

### ISSUE THREAD

**Issue by lorenzvee** [nefarius/ViGEm#68]
Hello,

thanks for your hard work.

My problem is this:

I installed the VigemBus driver with this command "devcon.exe install ViGEmBus.inf Root\ViGEmBus" and my result is "Drivers installed successfully" [Image](https://imgur.com/L1vCTN7)

However in my device manager i get this error: [image](https://imgur.com/Apv7tKV)

I'm using the x86 driver and VDX.exe because my tablet runs a 32 bit windows 10.

What could be my problem?

Thanks in advance

Bye

**Comment by djjinx1** [comment]
I also get this issue. I'm trying to emulate a DS4 via VDX.

Win 32 bit. Drivers seemed to install fine.

**Comment by nefarius** [comment]
What did you de besides installing the driver? The screenshot shows a child device with an error, not the bus.

**Comment by djjinx1** [comment]
I personally followed these steps to emulate a ps4 controller with a 360 pad

**Comment by djjinx1** [comment]
Devcon (Put in System32):

Uptobox:
http://uptobox.com/irgc79ob7s46

Google Drive:
https://drive.google.com/open?id=1N0Z...

ViGEm drivers (Put in System32, 32 or 64 bits):
 (Updated, Only ViGEm Bus drivers here without hidguardian and xnaguardian)

Uptobox:
http://uptobox.com/j0exa2w194xu

Google Drive:
https://drive.google.com/open?id=1mGI...

VDX (64bits works for me but not the 32bits, try if you want ;D):

Uptobox:
http://uptobox.com/3fev8gyfnht5

Google Drive:
https://drive.google.com/open?id=10Kf...

CMD COMMANDS: 

Install drivers:

devcon.exe install ViGEmBus.inf Root\ViGEmBus

**Comment by nefarius** [comment]
Maybe I goofed up the x86 builds, I only test the x64 builds to be honest since it's the majority of the target audience. You don't need to place anything yourself into system32/syswow64 btw.

**Comment by djjinx1** [comment]
Can you please check? I can test for you. Thanks

**Comment by nefarius** [comment]
@djjinx1 so you say 32-Bit driver works but VDX not? Did I get this right?

**Comment by zeiwander** [comment]
Hello!

Thanks for your contribution.

Is the same for me.

The VDX64 work perfect in windows 10 X64. but in windows 10 X32 dont work, I follow the steps:

Install devcon from X32
Install the driver from X32
Install c++ 
Install runtime from june 2010 (that have the driver)
Install X360CE and work.

When put on the VDX.exe, if selected the option xbox 1 controller, the system work and put the controller how to xbox one controller , and work with xbox remote with xbox one, and in the PC, and see the X360CE work perfect.

But, when selected dualshock 4 controller, the program freeze, that say, only with VDX.exe in windows 10 X32, in windows 10 X64 with VDX64.exe work perfect.

I try with my linx 8 vision with windows 10 X32.

Thanks from all, If you check these, I aprecciate.

**Comment by djjinx1** [comment]
VDX works for xbox controller but freezes when select dualshock 4.

I am on 32 bit windows linx vision 8.

I cannot tell if its app or driver??

**Comment by zeiwander** [comment]
Hello.

The linx vision 8 is a tablet, that incorporated the xbox controller in the tablet.

In the VDX.exe, when selected in controller 1, there are 2 options, xbox one and dualshock 4.

If selected xbox one controller and click and "connect", the button work, connect the controller and the button change to "disconnect", and when say the buttons from the xbox one controller in the X360CE, its ok.

The problem is when selected dualshock 4 controller and click in "connect", the program frezze and the button dont change to "disconnect".

For these problem, dont work in X32 with remote play for PS4

**Comment by nefarius** [comment]
We might need a remote session for this, you're welcome to [join me here](https://discord.gg/QTJpBX5).

**Comment by lorenzvee** [comment]
Thanks for your reply.

If you want i can give u full access to my tablet via teamviewer so you can test wherever you want at any time.

Now am at work and i cant give u any access. (Here are 16.48 /gmt+1/middle europe)

When i will be back i will log in discord and contact you.

If you are already testing with djjinx1 or zeiwander dont pay attention to my post.

Thanks

Bye

**Comment by djjinx1** [comment]
Nefarius has found the issue. Join discord bit later to help test :)

**Comment by lorenzvee** [comment]
Thanks djjinx1

I will

Bye :D
