### ISSUE TITLE
Bad signature on one of the pinvokes when using the .net wrapper

### ISSUE THREAD

**Issue by JoshWobbles** [nefarius/ViGEm#7]
Possibly int type mismatch somewhere in the wrapper, ill try to debug on my end but for now this is the exception I get:

PInvokeStackImbalance occurred
Message: Managed Debugging Assistant 'PInvokeStackImbalance' has detected a problem in 'C:\Users\jhebb\Documents\Visual Studio 2015\Projects\InputMapper1\InputMapper1\bin\Debug\InputMapper1.vshost.exe'.
Additional information: A call to PInvoke function 'ViGEmUM.NET!Nefarius.ViGEm.ViGemUm::vigem_target_plugin' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.

**Comment by JoshWobbles** [comment]
Easy fix
added CallingConvention = CallingConvention.Cdecl, think all is good now ;-)

**Comment by nefarius** [comment]
Pull requests welcome 😉

**Comment by JoshWobbles** [comment]
Still new to GH, i barely know how to branch and sync lol. Used to TFS but ill look up some vids on how and start contributing more, though my c++ kung-fu is pretty weak.

**Comment by nefarius** [comment]
No pressure!

**Comment by charlesmilette** [comment]
GitHub desktop (https://desktop.github.com) can do most of the things you
need without any knowledge required about git.

**Comment by nefarius** [comment]
I use [TortoiseGit](https://tortoisegit.org/) btw.

**Comment by charlesmilette** [comment]
Me too. But GitHub desktop is better for starters.

PS: Did you know I made the Win10 icon overlay theme?

**Comment by nefarius** [comment]
Hm, overlay, what? 😕

**Comment by charlesmilette** [comment]
This:

![image](https://cloud.githubusercontent.com/assets/6440374/20072703/5ef229b0-a4f7-11e6-9e8d-d887025584be.png)

**Comment by nefarius** [comment]
Oooooh no I didn't know 😄 small world, nice, I see them (nearly) every day 😃

**Comment by JoshWobbles** [comment]
Surely pull request has to be an option built into VS aswell.

**Comment by nefarius** [comment]
@JoshWobbles crash-course: you fork the repo you wanna contribute to on GitHub, clone this fork locally, make your fixes/modifications, push them back online and create a pull request via GitHub which automatically creates the diffs and notifies the original repo that a request is available for submission.

**Comment by charlesmilette** [comment]
@JoshWobbles The [GitHub Extension for Visual Studio](https://visualstudio.github.com/) has this feature.

@nefarius https://gitlab.com/tortoisegit/tortoisegit/blob/master/src/Resources/Icons/Win10/ReadMe.txt :P

**Comment by nefarius** [comment]
@charlesmilette ah, who reads readmes anyways 😜

**Comment by JoshWobbles** [comment]
I also alwayse seem to have mountains of issues getting forks to compile, so most my changes would be in the blind.
