### ISSUE TITLE
Installation issue (dependency missing?)

### ISSUE THREAD

**Issue by kozec** [nefarius/ViGEm#70]
Hello and sorry in advance, I'm Linux guy with very limited Windows knowledge.

I'm trying to port my Linux controller mapper to Windows using ViGEm for xinput "output" part. Somehow, I'm failing at step 1:

```
PS C:\Windows\system32> uname -a  # running as administrator
MSYS_NT-6.1 silver-w7 2.8.0(0.309/5/3) 2017-05-19 12:55 i686 Msys
PS C:\Windows\system32> Register-PSRepository -Name nuget.vigem.org -SourceLocation https://nuget.vigem.org/ -Installati
onPolicy Trusted
The term 'Register-PSRepository' is not recognized as the name of a cmdlet, function, script file, or operable program.
 Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:22
+ Register-PSRepository <<<<  -Name nuget.vigem.org -SourceLocation https://nuget.vigem.org/ -InstallationPolicy Truste
d
    + CategoryInfo          : ObjectNotFound: (Register-PSRepository:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

```

What kind of step 0 am I missing?

**Comment by nefarius** [comment]
Hey! Sorry I should add that to the docs; on Windows 7 you need to Upgrade to PowerShell version 5, I don't think you get it automatically via Windows Update. The "official" name is `Windows ManagementFramework`, [you can grab it here](https://www.microsoft.com/en-us/download/details.aspx?id=54616).

[Here's a nice overview](https://docs.microsoft.com/en-us/powershell/wmf/5.1/install-configure) with more information.

**Comment by kozec** [comment]
Thanks. Is there any chance to do this in less clunky way, ideally automatically? I don't like idea of installer that depends on .NET4.5 and specific version of powershell :(

**Comment by nefarius** [comment]
Yes, use `devcon` :P

Seriously though; .NET 4.5 and WMF 5.x are considered core components for many other purposes than my little installer. If I go all native I won't have sh*t finished until 2023. Installing those essential dependencies in 2017 is not much to ask. Like if you'd ask if you can get some software without apt. Not gonna happen. I consider this resolved.

**Comment by kozec** [comment]
Well, yeah, but if I need something from APT, I just declare it in dsc file and it gets installed automatically, while NET 4.5 and WMF 5.x has to be handled by user.

But if that's how things are, I'll just roll with it. Thanks for your answers :)

**Comment by nefarius** [comment]
Nope, the user has to handle nothing. A good setup program will handle detection and installation of required dependencies, even download them once online if necessary. The tools are all there for the Windows platform so I don't take that as an argument. I've dealt with all kinds of software distribution scenarios both in my free time and at work, don't reinvent the wheel, the tools are there, you can distribute .NET, WMF and ViGEm in a silent and unattended way. If you need directions I can help ofc.
