### ISSUE TITLE
An error a user got when trying to install the driver with Powershell on Windows 10 64bit

### ISSUE THREAD

**Issue by epigramx** [nefarius/ViGEm#71]
reported here: https://forum.cemu.info/showthread.php/140-WiimoteHook-Nintendo-Wii-Remote-with-Motion-Rumble-and-Nunchuk-support?p=1159&viewfull=1#post1159

He basically got what seems to be related to this issue https://stackoverflow.com/questions/35296482/invalid-web-uri-error-on-register-psrepository/35296483#35296483

"invalid Web Uri" possibly related to the address being https.

PS. On my end it works fine.

update: This is reported to be fixed on the anniversary update of Windows but I guess it might be interesting to know about it.

**Comment by nefarius** [comment]
Oh, PowerShell bugs, how delightful 😆 May I add your project to the README?

**Comment by epigramx** [comment]
Sure, go ahead.
