### ISSUE TITLE
How to use HIDGuardian?

### ISSUE THREAD

**Issue by jjensen6823** [nefarius/ViGEm#74]
I may be dense, but I can't figure out how to use this to block a joystick.  I am using vJoy to create a virtual controller, and Joystick Gremlin to configure it, both of which work perfectly.  The problem is that Elite: Dangerous VR registers the input from both the physical joystick and the virtual controller whenever I press a button.  In a support conversation for Joystick Gremlin, I saw HIDGuardian mentioned, so I followed the link and installed it.  The installer appeared to hang after installing everything, and after 10 minutes I killed the process.  It appears to be installed, but I can't figure out how to configure it.  Does this only work if InputMapper is also installed?  I also installed WhiteKnight, and installed it, then used it to install HIDCerberus.  I can follow the link in WhiteKnight to the internal web page and see all my devices, but when I click "Hide" for the one I want to hide, then unplug and replug it, it still shows up in the windows game controller window.  It may be obvious and I'm just clueless, but could you please tell me how to configure this properly?

**Comment by nefarius** [comment]
Be our guest: https://discord.gg/mfvA8B8
