### ISSUE TITLE
Just a question? Not an issue.

### ISSUE THREAD

**Issue by JoshWobbles** [nefarius/ViGEm#8]
Do all the virtual device's Mac addresses adhere to the convention of starting with "C0:13:37:", need an effective way to ignore virtual devices in InputMapper to avoid circular object creations. Im assuming so as all the devices ive created so far are beginning with C0:13:37:, but just want to make sure that isnt being generated from a constant on my machine such as HD,MoBo, or CPU serial .

**Comment by nefarius** [comment]
Yes, I "claimed" this space as mine and it's constant 😉

**Comment by JoshWobbles** [comment]
Perfect!

**Comment by nefarius** [comment]
Btw. the rest of the addresses are generated randomly but constant by slot index. They are stored in the registry: `HKLM\System\CurrentControlSet\Services\ViGEmBus\Parameters\Targets\DualShock\0\TargetMacAddress`

**Comment by JoshWobbles** [comment]
Index based on its own enumerator or in the case of 360 controllers based on "Player number"
