### ISSUE TITLE
vigem needs an unregister_******_notification method

### ISSUE THREAD

**Issue by JoshWobbles** [nefarius/ViGEm#9]
Garbage collection is an issue when disposing of a in use controller (only tested with DS4 right now) as when trying to dispose the device in c# sometimes vigem_target_unplug() is not quick enough to halt operation on a device and callbacks still in the queue sometimes call back to a disposed object throwing an exception.

**Comment by charlesmilette** [comment]
I love it that there are pertinent issues on ViGEm and FireShock because it's not been adopted widely yet.

**Comment by nefarius** [comment]
@JoshWobbles yup, ya right.

@charlesmilette what a relief I can tell ya 😜

**Comment by nefarius** [comment]
It's done!
